#!/bin/sh
#~/.config/zsh/aliasrc
#
# Aliasrc is a file created to house all of the shell alias definitions, written in this file for portability. (Used in conjunction with functionrc, then called in the zshrc file).

# This removes all user-defined aliases just to avoid any potential issues when changing names of
# aliases.
unalias $(alias | cut -f 1 -d '=' | paste -s -d ' ') 2>/dev/null

### Old methods of clearing aliases:
	# unalias $(alias | cut -f 1 -d '=' | tr '\n' ' ')
	# unalias $(alias | cut -f 1 -d '=' | paste -s -d ' ')
	# unalias $(alias | sed -e 's/=.*$//' | sed ':a;N;$!ba;s/\n/ /g')

# Sudo aliases.
alias sudo='sudo '	 		# Stupid fix for being able to use aliases with sudo.					
alias sE='sudo -E '			# Alias to run sudo command but keep current environment variables.	
alias se='sudo -E $EDITOR '	# Alias to preserve current user's environment vars, and open $EDITOR.
alias sv='sudo -E nvim '	# Alias to open a file in nvim as sudo.
#alias s='sudo'				# Depreciated. This is now in the functionrc file, and can repeat the
							# previous command as sudo, and functions as an alias the same way it
							# used to when defined here. (The other sudo aliases needed a full
							# "sudo" in the definitions as a result of this however, but is better
							# practice to do this anyways rather than having recursive aliases).

# Shortened browser/editor aliases.
alias \
	r='ranger'	\
	h='hunter ' \
	v='nvim '	\
	m='neomutt' \
	n='ncmpcpp' \
	t='tmux'

# Edit config file shortcuts.
alias \
	zrc='v ~/.config/zsh/.zshrc'						\
	zr='. ~/.config/zsh/.zshrc'							\
	nrc='v ~/.config/nvim/init.vim'						\
	tmc='v ~/.tmux.conf'								\
	arc='v ~/.config/zsh/aliasrc'						\
	frc='v ~/.config/zsh/functionrc'					\
	tmpv='v /tmp/tempfiles/`date "+%m-%d-%Y_%H-%M-%S"`'	
# Creates the directory "/tmp/tempfiles/" if it doesn't exist already.
[[ ! -d /tmp/tempfiles ]] && mkdir /tmp/tempfiles

# Automatically specifying options always used to a shortened alias for core file programs/utils.
alias \
	ls='ls --color=always'	\
	lt='ls -lth'			\
	l='ls -lh'				\
	la='ls -lah'			\
	lt='ls -lath'			\
	mv='mv -v'				\
	cp='cp -v'

# Directory shortcuts.
alias \
	b='cd ..'											\
	..='cd ..'											\
	.1='cd ..'											\
	.2='cd ../..'										\
	.3='cd ../../..'									\
	conf='cd ~/.config'									\
	confn='cd ~/.config/nvim'							\
	nconf='cd ~/.config/nvim'							\
	zconf='cd ~/.config/zsh'							\
	mn='cd /mnt'										\
	mnt='cd /mnt'										\
	tmp='cd /tmp'										\
	tmpvcd='cd /tmp/tempfiles'							\
	d='cd ~/Documents'									\
	D='cd ~/Downloads'									\
	p='cd ~/Documents/programming'						\
	pub='cd /mnt/Data/Public'							\
	priv='cd /mnt/Data/Drew'							\
	nvc='cd ~/.config/nvim'								\
	dot='cd ~/Documents/git/dotfiles'					\
	ba='cd ~/Documents/programming/bash'				\
	py='cd ~/Documents/programming/python'				\
	py2='cd ~/Documents/programming/python/2'			\
	py3='cd ~/Documents/programming/python/3'			\
	cryptd='cd /mnt/crypt'								\
	luksd='cd /mnt/crypt/luks'							\
	m='cd ~/Music'										\
	aptc='cd /etc/apt/'									\
	work='cd ~/Documents/Work/'							\
	r2s='cd ~/Documents/Work/Ready2Show'				\
	r2sd='cd ~/Documents/Work/Ready2Show/Development/'	\
	P='cd ~/Pictures'									\
	hm='cd ~/Mountpoints'								\
	hmnt='cd ~/Mountpoints'								\
	E='cd ~/Documents/Education'						\
	certs='cd ~/Documents/Education/Certs'

# General quality of life improvements and aliasing lengthy commands.
	alias 																		\
		ncmpcpp='ncmpcpp -b ~/.config/ncmpcpp/bindings'							\
		cgrep='grep --color=always'												\
		cgrep='grep --color=always'												\
		cg='grep --color=auto'													\
		icg='grep -i --color=auto'												\
		cgi='grep -i --color=auto'												\
		igp='grep -i --color=auto'												\
		g='cd $HOME/Documents/git'												\
		gd=g																	\
		gc='git clone '															\
		c='/usr/local/bin/colorchart'											\
		less='less -R'															\
		diff='diff --color=auto'												\
		ip='ip --color=always'													\
		fm='q pcmanfm-qt'														\
		bt='bashtop'															\
		mdl='youtube-dl --config-location ~/.config/youtube-dl/mconfig '		\
		myt='youtube-dl --config-location ~/.config/youtube-dl/mconfig '		\
		mytd='youtube-dl --config-location ~/.config/youtube-dl/mconfig '		\
		ytd='youtube-dl '														\
		ytdl='youtube-dl '														\
		nics='sudo ifconfig | plx'												\
		paux='ps aux'

# Less command aliases
	alias							\
		le='less'					\
		lx='less -X'				\
 		ple='pcat | less -X'		\
		cle='pcat "$@" | less -X'	\
		plx='pcat | less -X'		\
		clx='pcat | less -X'

####################################################################################################
##################################### Package manager aliases. #####################################
####################################################################################################

#######################
### Aliases for apt.###
#######################
# Aliases for various apt commands; updates python-pip
alias									\
	ins='sudo apt-get install '			\
	insf='sudo apt-get install '		\
	ac='apt-cache '						\
	aci='apt-cache --installed '		\
	acs='apt-cache search '				\
	ag='apt-get '						\
	adeps='apt-rdepends '				\
	aure='apt-get autoremove '			\
	aurep='apt-get autoremove --purge '	

# Alias to update and upgrade all python-pip packages.
	alias pipup='pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 \
		| xargs -n1 pip3 install -U'

# File ownership/permission aliases.
	alias							\
		cx='chmod +x '				\
		chx='chmod +x '				\
		chmx='chmod +x '			\
		mine='chown $USER:$GROUP '

# Network aliases.
# Sortcuts for connecting to sessions.
# Supposedly SSH might break if the remote machine does not have the same $TERM variable.
# [Unsure of this since the environment variables are applied in each host's session.]
	#alias ssh='TERM=xterm-direct ssh'			# Commenting this out for now.
	#alias seedbox='ssh -l pi -p 9999 192.168.1.28'
	#alias seedbox='ssh -l drew -p 9999 192.168.1.28'
	alias pi2='ssh -l pi -p 9999 192.168.1.28'
	alias nas='ssh -l drew -p 9999 -Y 192.168.1.31'
	alias cs='ssh -l cisco 192.168.1.2'
	alias cr='ssh -l cisco 192.168.1.3'
	alias tmr='tmux attach-session'
	
	# Alias to connect to NordVPN's auto-selected fastest server over UDP.
	#alias vpn='sudo \
	#	openvpn /etc/openvpn/NordVPN/ovpn_udp/us4396.nordvpn.com.udp.ovpn'
	#alias vpn='sudo \
	#	openvpn /etc/openvpn/NordVPN/ovpn_udp/us6449.nordvpn.com.udp.ovpn'
	# Alias below should be a function that automatically determines the fastest server (optionally
	# specifying the region), but for now Denver OpenVPN server will be hard-coded to the alias.
	alias fastopenvpn='sudo openvpn \
		/etc/openvpn/client/Torguard/Torguard-ALL_SERVERS.ovpn'
	#alias evpn='expressvpn connect'
	#alias torrentvpn='expressvpn connect "Switzerland"'
	#alias torrentvpn2='expressvpn connect "Switzerland 2"'
	#alias safevpn='expressvpn connect "Switzerland 2"'
	#alias safevpn2='expressvpn connect "Switzerland 2"'

	alias pubip='dig +short johnstonnetwork.asuscomm.com | tail -n1'
	alias myip='curl icanhazip.com'

# Alias to display the current running aliases in fuller in a less -R (aliases 
