#!/bin/sh
#~/.config/zsh/aliasrc
#
# Aliasrc is a file created to house all of the shell alias definitions, written in this file for portability. (Used in conjunction with functionrc, then called in the zshrc file).

# Stupid fix for being able to use aliases with sudo.
alias sudo='sudo '

# Alias for preserving the user's environment in sudoedit
alias \
	sudoe='sudo -E nvim ' \
	se='sudo -E nvim '
	#sudoedit='sudo -E nvim ' \

# Shortened browser/editor aliases.
alias \
	r='ranger' \
	h='hunter ' \
	v='$EDITOR' \
	m='neomutt' \
	n='ncmpcpp' \
	t='tmux'

# Edit config file shortcuts.
alias \
	zrc='v ~/.zshrc' \
	zrcr='. ~/.zshrc' \
	zr='. ~/.zshrc' \
	nrc='v ~/.config/nvim/init.vim' \
	tmc='v ~/.tmux.conf' \
	arc='v ~/.config/zsh/aliasrc'
	frc='v ~/.config/zsh/functionrc'

# Automatically specifying options always used to a shortened alias.
alias \
	ls='ls --color=auto' \
	lt='ls -lth' \
	mv='mv -v' \
	l='ls -lh' \
	la='ls -lah' \
	lt='ls -lath' \

# Directory shortcuts.
alias \
	conf='cd ~/.config' \
	mn='cd /mnt' \
	tmp='cd /tmp' \
	d='cd ~/Documents' \
	p='cd /home/drew/Documents/programming' \
	pub='cd /mnt/Data/Public' \
	priv='cd /mnt/Data/Drew' \
	b='cd ..' \
	nvc='cd ~/.config/nvim' \
	dot='cd ~/Documents/git/dotfiles' \
	ba='cd ~/Documents/programming/bash' \
	crypt='cd /mnt/Data/Drew/crypt'
	# Commented out for now since theres no use or reason to have it aliased.
	#netlogs='cd /mnt/Data/Drew/Documents/Network\ info/Network\ Logs/' \

# General quality of life improvements and aliasing lengthy commands.
	# Alias to upgrade all python3 pip packages and package manager shortcuts.
		alias pip-upgrade='pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | \
			xargs -n1 pip3 install -U'
		alias pip-update='pip-upgrade'
		alias pipupdate='pip-upgrade'
		alias pipupgrade='pip-upgrade'
		alias ins='sudo apt-get install '
		alias ncmpcpp='ncmpcpp -b ~/.config/ncmpcpp/bindings'
	# Alias/linking batcat to bat
		#alias bat='batcat '
	# Alias to colorize STDIN (Standard Input) using pygmentize.
		alias colorstdin='pygmentize -f terminal256 -O style=monokai'
		alias cgrep='grep --color=always'
	# Alias to truncate git clone.
		alias gc='git clone '

# Shortcuts for connecting to sessions.
	# Supposedly SSH might break if the remote machine does not have the same $TERM variable.
		alias ssh='TERM=xterm-direct ssh'
	# Shortcut to ssh into seedbox as pi user.
		alias sshpi='ssh -l pi -p 9999 192.168.1.28'
		alias sshpi2='ssh -l rtorrent -p 9999 192.168.1.28'
		alias sshseedbox='ssh -l rtorrent -p 9999 192.168.1.28'
		alias sshnas='ssh -Y -l drew -p 9999 192.168.1.31'
	# Reconnect to first instance of tmux in ps for current user.
		alias tmr='tmux attach-session'

# Functions.
	# Function to mkdir $1 and cd into it.
		function mkcd {
		    mkdir -p "$1" && cd "$1"
		}

	# Alias for colored cat outputs (bat uses a man page type interface with scrolling, whereas pcat is just
	# pygmentized cat standard output in the terminal).
		function pcat {
			cat "$1" | pygmentize -f terminal256 -O style=monokai
		}
	# Function to make `sudoedit` and `sudo -e` have propper syntaxing with filetype autodetect working.
	#	function sudoedit {
	#		SUDO_COMMAND="sudoedit $@" command sudoedit "$@"
	#	}
	# Function for using `sudo -e` just linking to sudoedit
	
	# Function to git clone a directory, then cd into it.
		gcd(){
			git clone "$1" && cd "$(basename "$1" .git)"
		}
#	# Function to easily kill screen PIDs without having to manually type them out.
#		sk(){
#			SCREENPIDS="$(screen -ls | sed -e 1d -e '$d' | cut -d '.' -f 1 | tr -d '\t')"
#			echo $SCREENPIDS
#		}
