#!/bin/sh
# Filter for `less` command to colorize it using pygmentize.

# Commenting this out to apply this filter to every less command usage (prolly should just figure out how to
# add stdout to this filter but am lazy).

#	case "$1" in
#	    *.awk|\
#		*.groff|\
#		*.java|\
#		*.js|\
#		*.m4|\
#		*.php|\
#		*.pl|\
#		*.pm|\
#		*.pod|\
#		*.sh|\
#	    *.ad[asb]|\
#		*.asm|\
#		*.inc|\
#		*.[ch]|\
#		*.[ch]pp|\
#		*.[ch]xx|\
#		*.cc|\
#		*.hh|\
#	    *.lsp|\
#		*.l|\
#		*.pas|\
#		*.p|\
#		*.xml|\
#		*.xps|\
#		*.xsl|\
#		*.axp|\
#		*.ppd|\
#		*.pov|\
#	    *.diff|\
#		*.patch|\
#		*.py|\
#		*.rb|\
#		*.sql|\
#		*.ebuild|\
#		*.eclass|\
#		*.vim)
#			pygmentize -f 256 "$1";;
#	
#	    .zshrc|aliasrc|.zshenv)
#	        pygmentize -f 256 -l sh "$1";;
#	
#	    *)
#	        if grep -q "#\!/bin/bash" "$1" 2> /dev/null; then
#	            pygmentize -f 256 -l sh "$1"
#	        else
#	            exit 1
#	        fi
#	esac

#pygmentize -f terminal256 -O style=monokai -g "$1"

#exit 0

####################################################################################################
## Added this list of color configs for less command to make it look nicer when reading man pages ##
##                      https://unix.stackexchange.com/a/147/401241                               ##
####################################################################################################
export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
export LESS_TERMCAP_md=$(tput bold; tput setaf 6) # cyan
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) # yellow on blue
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7) # white
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)
export GROFF_NO_SGR=1         # For Konsole and Gnome-terminal
